# Server
server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/Movies_db?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=1234

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.auto-commit=false

# JPA Batch Processing
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true

# Logging (solo per debug)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.transaction=DEBUG
spring.jpa.show-sql=false

# Abilita la generazione della documentazione
springdoc.api-docs.enabled=true

# Personalizza il path della UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs